version: '3.8'
services:
  web:
    build: .
    ports:
      - '5000:5000'
    environment:
      - FLASK_ENV=development #Switch [development,production]
      - FLASK_APP=app/entrypoint/handler_entrypoint.py
      - SECRET_KEY=my_secret_key
      - DATABASE_URL=postgresql://n5admin:n5secret@db/n5challenge
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=n5challenge
      - POSTGRES_USER=n5admin
      - POSTGRES_PASSWORD=n5secret

volumes:
  postgres_data:
